services:
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - goli-network
