version: "3.8"

services:
  mysql:
    image: bitnami/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME:-"goli"}
      MYSQL_USER: ${DB_USER:-"goli"}
      MYSQL_PASSWORD: ${DB_PASSWORD:-"asdf1234"}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-"asdf1234"}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/bitnami/mysql/data
    networks:
      - goli-network

  typesense:
    image: typesense/typesense:0.25.1
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - typesense-data:/data
    command: "--data-dir /data --api-key=${NEXT_PUBLIC_TYPESENSE_API_KEY} --enable-cors"
    networks:
      - goli-network

volumes:
  mysql-data:
  typesense-data:

networks:
  goli-network:
    driver: bridge
