version: "3.8"

services:
  mysql:
    image: mysql:8.2.0
    restart: always
    environment:
      MYSQL_DATABASE: "db_goli"
      MYSQL_USER: "goli"
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-"goli"}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-"hgSIchuQJG"}
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - goli-network

  typesense:
    image: typesense/typesense:0.25.1
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - typesense-data:/data
    command: "--data-dir /data --api-key=a3c3cb2572e5f7a2 --enable-cors"
    networks:
      - goli-network

volumes:
  mysql-data:
  typesense-data:

networks:
  goli-network:
    driver: bridge
