services:
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-"hgSIchuQJG"}
    networks:
      - mysql-phpmyadmin

  mysql:
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:
